package com.dynss.cloudtecnologia.model.enums;

public enum Natureza {
    ALIMENTACAO, SAUDE, ESPORTES, ESTUDOS, TRANSPORTE, LAZER,
    EMPRESTIMO, GASTOS_PESSOAIS, REMUNERACAO, CARTAO_DE_CREDITO,
    ACADEMIA, RENDIMENTO, EMPRESTIMO_CARTAO, TAXAS_BANCARIAS, SERVICOS,
    TECNOLOGIA;

}
